version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ocean-hazard-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ocean_hazard_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - ocean-hazard-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocean-hazard-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/ocean_hazard_db?authSource=admin
      - DB_NAME=ocean_hazard_db
      - CORS_ORIGINS=http://localhost:3000
      - EMERGENT_LLM_KEY=sk-emergent-6C726E321B0C704Eb5
    depends_on:
      - mongodb
    networks:
      - ocean-hazard-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ocean-hazard-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    networks:
      - ocean-hazard-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  ocean-hazard-network:
    driver: bridge
